version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - "yarn install --frozen-lockfile"
  build:
    commands:
      # - printenv > .env
      - "yarn build"
  post_build:
    commands:
      - echo Synchronizing S3 bucket directory $S3_BUCKET ...
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
        aws s3 sync ./build $S3_BUCKET;
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*";
        else
        echo Build failed ignoring deployment;
        fi
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
cache:
  paths:
    - ".cache/*"
    - "public/*"
