version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - "yarn install --frozen-lockfile"
  build:
    commands:
      # - printenv > .env
      - yarn build
      # - CI=true yarn test
  post_build:
    commands:
      - echo Synchronizing S3 bucket directory $S3_BUCKET ...
      - aws s3 sync ./build $S3_BUCKET;
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*";
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
cache:
  paths:
    - ".cache/*"
    - "public/*"
